apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: rhoc-addon
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/abrianik/addon-connectors-operator-catalog:latest
